### ISSUE TITLE
Inherit all does not work.

### ISSUE THREAD

**Issue by andriassundskard** [kaymer327/mRemote3G#3]
Create a folder and specify username, password and domain.

Create a host under that folder and "inherit all" under inheritance tab.

Go back to properties tab. "Object reference not set to an instance of an object." are listed in fields "Username", "Gateway Hostname", "Gateway Username" and "Smart Cards".

When double clicking the host it will ask for username and password.

**Comment by kaymer327** [comment]
This appears to be caused by commit: 5f2112a6948469828502aaaec1cdd648abae9303 

Looking to revert this change.

**Comment by kaymer327** [comment]
Fixed in Version [1.91](https://github.com/kaymer327/mRemote3G/releases/tag/1.91)
