### ISSUE TITLE
Inheritance not working properly

### ISSUE THREAD

**Issue by thecosmictrickster** [kaymer327/mRemote3G#4]
When using a configuration file from mRemoteNG, several fields do not inherit properly. The error message "Object reference not set to an instance of an object" is displayed. After exiting and starting up again, I am inundated with messages stating much the same thing - one for each connection with inheritance it appears (see attached). This also happens when creating a new connection file. It applies to both folders and files.

![mremote3g_err1](https://cloud.githubusercontent.com/assets/16566436/12129933/a2343d76-b46b-11e5-8e7e-2f231febf464.png)
![mremote3g_err2](https://cloud.githubusercontent.com/assets/16566436/12129938/aa077540-b46b-11e5-9004-750b1bbdbff5.png)

**Comment by kaymer327** [comment]
This appears to be a duplicate of #2. 

I just posted build [1.91](https://github.com/kaymer327/mRemote3G/releases/tag/1.91) to fix that one. Test it out and let me know if it resolves this issue as well.

**Comment by andriassundskard** [comment]
This were the same problems that I had in 1.90 when I created issue #3. Version 1.91 seems to have fixed this.

**Comment by thecosmictrickster** [comment]
Yes, fixed.
Thanks.
